### ISSUE TITLE
Release Subjects200K dataset on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [Yuanshi9815/Subjects200K#1]
Hello @Yuanshi9815,

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through AK's daily papers, the paper page is here: https://huggingface.co/papers/2411.15098.

The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance), you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the datasets you've released on https://huggingface.co/datasets? Hosting on Hugging Face will give you more visibility/enable better discoverability, and will also allow people to do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org-or-username/your-dataset")
```

If you're down, leaving a guide here: https://huggingface.co/docs/datasets/en/image_dataset. We also support Webdataset, useful for image/video datasets: https://huggingface.co/docs/datasets/en/loading#webdataset.

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

After uploaded, we can also link the datasets to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your work.\n\nLet me know if you're interested/need any guidance.

Kind regards,

Niels

**Comment by cfahlgren1** [comment]
+1 would love to be able to paginate through the images in the dataset viewer

**Comment by Yuanshi9815** [comment]
Hi Niels @NielsRogge,

Thank you for reaching out and for your interest in my paper.

I'm currently working on preparing the dataset following the guidelines, but I've encountered a performance issue during the preparation process. Specifically, in the `ArrowBasedBuilder._prepare_split_single` function, while generating the train split, I only get about 3.8 examples processed per second. 

```
Downloading data: 100%|██████████| 206842/206842 [00:02<00:00, 74571.75files/s] 
Generating train split: 6912 examples [29:26,  3.83 examples/s]
```

At this rate, processing my 200k examples would take approximately 14 hours. Is this the expected performance, or is there something in my implementation that could be optimized?



I would appreciate any guidance on this matter.

Best regards
Stone

**Comment by NielsRogge** [comment]
Hi, thanks for your reply.

Do you have a code reproducer? Then I can ping some people from the HF team to help you out.

**Comment by Yuanshi9815** [comment]
Hi, Niels @NielsRogge

I have solved this problem by setting `num_proc=64`. The dataset has now been completely uploaded to Hugging Face.

Best regards,
Stone
